### ISSUE TITLE
Geen issue maar kleine wens

### ISSUE THREAD

**Issue by nldroid** [Scriptman/ESPHome_ITHO_Eco_Fan_CC1101#2]
Super dat je deze beschikbaar gemaakt hebt voor esphome. Ik heb al veel esphome devices in mijn huis dus deze past daar mooi bij.

Op dit moment heb ik de versie voor ESPEASY van jodur en die heeft ook een 'stand by' stand. Die van jou heeft als laagste stand 'Low'.

Ik kan het waarschijnlijk wel zelf toevoegen maar wil nu even niet experimenteren met mijn setup. Als ik er aan toe ben, en je hebt het zelf nog niet toegevoegd, doe ik wel een pull request.

**Comment by Scriptman** [comment]
Hey, bedankt voor je bericht. Ik zal dit weekend nog eens kijken. Volgens mij zit het al half er in. Ik heb deze code vanuit 3 of 4 git repos samengevoegd, en nog zelf wat aangepast omdat geen enkele code werkte voor mij.

Mvg.

**Comment by Scriptman** [comment]
@nldroid Ik heb het voor elkaar gekregen! Ik zal ergens vanavond of morgen even de code updaten!

**Comment by TychoWerner** [comment]
> @nldroid Ik heb het voor elkaar gekregen! Ik zal ergens vanavond of morgen even de code updaten!

Hallo Scriptman,

Is deze aanpassing al doorgevoerd of is hij misschien blijven hangen? Heel erg tof dit allemaal en binnenkort onderdelen bestellen voor mij zelf.

**Comment by MarioL1989** [comment]
@TychoWerner Het is even blijven hangen, ben bezig met een server migratie, daarvoor bezig geweest in de tuin en met het huis, dus het loopt wat vertraging op allemaal, mijn excuses!

**Comment by Scriptman** [comment]
@TychoWerner @nldroid Heeft langer geduurd dan gewenst, maar de aanpassingen zijn doorgevoerd. Code is geüpdatet en je kan nu zien welke afstandsbediening als laatste ingedrukt is.
