### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ragelink574** [Scriptman/ESPHome_ITHO_Eco_Fan_CC1101#3]
waarschijnlijk een domme fout van mij, maar ik krijg bij het compileren de volgende fout:
src/main.cpp: In lambda function:
src/main.cpp:207:29: error: expected type-specifier before 'FanSendLow'
       auto fansendlow = new FanSendLow();
                             ^
src/main.cpp:209:25: error: could not convert '{fansendlow}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendlow};
                         ^
src/main.cpp: In lambda function:
src/main.cpp:216:32: error: expected type-specifier before 'FanSendMedium'
       auto fansendmedium = new FanSendMedium();
                                ^
src/main.cpp:218:28: error: could not convert '{fansendmedium}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendmedium};
                            ^
src/main.cpp: In lambda function:
src/main.cpp:225:30: error: expected type-specifier before 'FanSendHigh'
       auto fansendhigh = new FanSendHigh();
                              ^
src/main.cpp:227:26: error: could not convert '{fansendhigh}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendhigh};
                          ^
src/main.cpp: In lambda function:
src/main.cpp:234:28: error: expected type-specifier before 'FanSendIthoTimer1'
       auto fansendt1 = new FanSendIthoTimer1();
                            ^
src/main.cpp:236:24: error: could not convert '{fansendt1}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendt1};
                        ^
src/main.cpp: In lambda function:
src/main.cpp:242:28: error: expected type-specifier before 'FanSendIthoTimer2'
       auto fansendt2 = new FanSendIthoTimer2();
                            ^
src/main.cpp:244:24: error: could not convert '{fansendt2}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendt2};
                        ^
src/main.cpp: In lambda function:
src/main.cpp:250:28: error: expected type-specifier before 'FanSendIthoTimer3'
       auto fansendt3 = new FanSendIthoTimer3();
                            ^
src/main.cpp:252:24: error: could not convert '{fansendt3}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendt3};
                        ^
src/main.cpp: In lambda function:
src/main.cpp:258:30: error: expected type-specifier before 'FanSendIthoJoin'
       auto fansendjoin = new FanSendIthoJoin();
                              ^
src/main.cpp:260:26: error: could not convert '{fansendjoin}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::switch_::Switch*>'
       return {fansendjoin};
                          ^
src/main.cpp: In lambda function:
src/main.cpp:266:26: error: expected type-specifier before 'FanRecv'
       auto fanrecv = new FanRecv();
                          ^
src/main.cpp:268:50: error: could not convert '{<expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::text_sensor::TextSensor*>'
       return {fanrecv->fanspeed,fanrecv->fantimer};

**Comment by Scriptman** [comment]
https://github.com/Scriptman/ESPHome_ITHO_Eco_Fan_CC1101/issues/1

;)

**Comment by ragelink574** [comment]
Hoi

Dank je, maar wat gaat er mis? De validatie stap gaat goed.

Groet
Rob

Verstuurd vanaf mijn iPhone

**Comment by MarioL1989** [comment]
Hallo Rob,

Dat is moeilijk te zeggen, je hebt niet je configuratie bestanden of iets dergelijks gestuurd.
Het ticket waar ik naar verwijs, #1 had dezelfde foutmeldigen als jij nu hebt. Belangrijk is om te controleren of de CC1101.h file aangemaakt is zoals beschreven in stap "Add the cc1101.h file (interface class to include/use the CC1101 library)"

Controleer ook je device config in ESPHome. Controleer of je de "includes" en "libraries" hebt toegevoegd:
```
esphome:
  name: itho_eco_fan
  platform: ESP8266
  board: d1_mini_pro
  includes: 
    - itho_eco_fan/itho/cc1101.h
  libraries: 
    - https://github.com/Scriptman/ESPHome_ITHO_Eco_Fan_CC1101.git
```

**Comment by ragelink574** [comment]
Top, het werkt.
Dank je

Groet
Rob

> Op 20 mrt. 2020, om 14:35 heeft MarioL1989 <notifications@github.com> het volgende geschreven:
> 
> sphome:
>   name: itho_eco_fan
>   platform: ESP8266
>   board: d1_mini_pro
>   includes: 
>     - itho_eco_fan/itho/cc1101.h
>   libraries: 
>     - https://github.com/Scriptman/ESPHome_ITHO_Eco_Fan_CC1101.git <https://github.com/Scriptman/ESPHome_ITHO_Eco_Fan_CC1101.git>
>

**Comment by Scriptman** [comment]
Fijn dat het werkt!
