### ISSUE TITLE
Ook geen issue, maar waarschijnlijk grotere wens......

### ISSUE THREAD

**Issue by Haringstad** [Scriptman/ESPHome_ITHO_Eco_Fan_CC1101#4]
Eerst wil ik je heel erg bedanken, voor alle moeite die je hierin hebt gestoken! Het werkt geweldig! Uiteraard kom je met het knutselen er achter dat de module maar een zeer beperkt bereik heeft, en dat dit echt niet aan de software ligt! 
Paren van de Itho en de ESP, was een eitje! Bij poging: 1! Werken! Kortom, top!!!

Maar je weet het, HA gebruikers willen altijd **meer** van het goede. Nu heeft Jodur een ESPHome versie er uit geknutseld, die perfect met de nieuwere versies van de ITHO werkt, maar niet met de oude. 

Nu is mijn verzoek, is het mogelijk om de functionaliteit van https://github.com/jodur/ESPHOME-ITHO ook in jouw versie te krijgen? Met andere woorden, dus ook kunnen zien welke "afstandsbediening" als laatste de opdracht heeft gegeven? En wat meer dingetjes? Man, dat zou het zo super maken!!!

En, **nee** is ook een heel net, en acceptabel antwoord!

EDIT: Ik ben zelf al een week of 2 aan het knoeien met de code, maar ik kom er echt niet uit.....

**Comment by Scriptman** [comment]
Hallo @Haringstad 

Bedankt voor je bericht en interesse. Excuses voor de latere reactie i.v.m. vakantie.
Ik zal de libraries eens naast elkaar leggen en kijken wat er veranderd is.
Helaas kan ik niet beloven dat ik dit binnen enkele dagen kan doen, maar ik zal je op de hoogte houden!

Mvg,
Mario

**Comment by Haringstad** [comment]
Mario, geen probleem!!! Absoluut geen probleem ;-)
Ik ben al heel blij dat je er naar wilt kijken!!!
SUPER en DANK JE WEL!

Regards,

Jacco van Koll

**Comment by Scriptman** [comment]
@Haringstad Code is geüpdatet en je kan nu zien welke afstandsbediening als laatste ingedrukt is.
