### ISSUE TITLE
ESP node reboot tijdens een cmd

### ISSUE THREAD

**Issue by Uncapable** [Scriptman/ESPHome_ITHO_Eco_Fan_CC1101#5]
Hoi Mario,

Ik heb mn esp geflashed met jouw code. Ik kwam van de esp easy methode af, maar de esphome manier vond ik veel interessanter.
Nu is het flashen goed gelukt met behulp van jouw stappen plan. Maar nu.
Gisteravond had ik de boel werkend, ik kon de esp laten joinen met de ITHO en commands sturen vanuit HA.
Sinds vanmorgen werkt het niet meer, ook niet na een nieuwe reflash en het al dan niet opnieuw aanmelden in HA.

Ik kan de logs zien via ESP easy, en daar zie je dus dat de node reboot na een willekeurig commando.

←[0;36m[D][switch:021]: 'FanSendJoin' Turning ON.←[0m

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffb40 end: 3fffffc0 offset: 01a0
3ffffce0:  3fff1ced 000000f5 3fff09f0 40215a34
3ffffcf0:  3fff09f0 000000f5 3fff1340 40215b88
3ffffd00:  3fff09f0 3ffffda9 00000035 40215b1d
3ffffd10:  0000000f 000000f5 3fff09f0 40215c3b
3ffffd20:  00000013 3ffffda9 3fff09f0 40215e89
3ffffd30:  3fff09f0 3fff09f0 00000000 00000003
3ffffd40:  00000028 00000000 3fff09f0 00000003
3ffffd50:  00000028 00000000 3fff09f0 40216c53
3ffffd60:  aaaaaa48 aaaaaaaa b300feab 952aab2a
3ffffd70:  9a59659a 9a69aa99 69a55556 a55aaa5a
3ffffd80:  556a59a5 96596695 5965a5aa 69aa999a
3ffffd90:  a555569a 6a565969 9a596595 9a69aa99
3ffffda0:  aaa99a56 aaaaaaca aaaa13aa 5333adaa
3ffffdb0:  cc542b33 5455abaa abaab4ca 3fff2755
3ffffdc0:  3ffffe90 3fff273c 3fff2810 4020c0c0
3ffffdd0:  3ffffe20 3ffffe10 00000010 4022e86c
3ffffde0:  00210000 00040000 00010000 4020c0ec
3ffffdf0:  3ffffe20 3ffffe10 00000010 402143ee
3ffffe00:  3ffffe20 3ffffe10 00000010 3fff2740
3ffffe10:  3ffffe90 3fff273c 3fff2804 4020d13b
3ffffe20:  3fff2860 00000002 3fff2810 4020d16a
3ffffe30:  3ffffe90 00000007 00000006 40207098
3ffffe40:  00001401 3fff3c6c 3fff2810 40201160
3ffffe50:  aec92ade 3fff172c 00000001 40229d69
3ffffe60:  00000002 3ffffe80 00000010 00000003
3ffffe70:  00000007 3ffffe90 3fff3a5c 40220066
3ffffe80:  00000007 00000007 3fff3a5c 40204795
3ffffe90:  40221608 aec92ade 00000001 14395810
3ffffea0:  00000000 00000000 3ffffed0 00000002
3ffffeb0:  0000000a 00000007 3fff3a5c 40201a07
3ffffec0:  00000001 00000000 00000021 00000000
3ffffed0:  00000001 00000000 00000007 00000000
3ffffee0:  00000001 4bc6a7f0 00003960 40208138
3ffffef0:  00000000 3fff2008 3fff3a5c 3fff2364
3fffff00:  3fff2008 3fff2008 3fff3a5c 40201aa8
3fffff10:  00000000 00000000 4bc6a7f0 00000000
3fffff20:  3fff34dc 00000002 3fff2364 40204d72
3fffff30:  3fff34e0 00000002 3fff0928 40220668
3fffff40:  3fff34e0 00000002 3fff0928 402206fd
3fffff50:  3fffdad0 00000002 3fff0928 4020a5f3
3fffff60:  007a1200 c009fe77 3fff2400 3fff2400
3fffff70:  3fff34e4 feefeffe feefeffe feefeffe
3fffff80:  00000000 00000000 00000001 3fff0db0
3fffff90:  3fffdad0 00000000 3fff0d70 4020d4d0
3fffffa0:  3fffdad0 00000000 3fff0d70 4021dd78
3fffffb0:  feefeffe feefeffe 3ffe8524 40100625
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3584, room 16
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
←[0;32m[I][logger:166]: Log initialized←[0m
←[0;35m[C][ota:366]: There have been 1 suspected unsuccessful boot attempts.←[0m
←[0;32m[I][app:029]: Running through setup()...←[0m
←[0;35m[C][wifi:033]: Setting up WiFi...←[0m
←[0;36m[D][wifi:324]: Starting scan...←[0m
←[0;36m[D][text_sensor:015]: 'FanSpeed': Sending state 'Low'←[0m
←[0;36m[D][text_sensor:015]: 'FanTimer': Sending state '0'←[0m
←[0;36m[D][wifi:339]: Found networks:←[0m
←[0;32m[I][wifi:385]: - 'Unifi Airport' ←[5m(78:8A:20:D7:8E:5C) ←[6m←[0;32mÔûéÔûäÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:386]:     Channel: 6←[0m
←[0;36m[D][wifi:387]:     RSSI: -44 dB←[0m
←[0;32m[I][wifi:385]: - 'Unifi Airport' ←[5m(FC:EC:DA:11:F4:28) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:386]:     Channel: 1←[0m
←[0;36m[D][wifi:387]:     RSSI: -73 dB←[0m
←[0;32m[I][wifi:385]: - 'Unifi Airport' ←[5m(18:E8:29:EA:48:9A) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:386]:     Channel: 6←[0m
←[0;36m[D][wifi:387]:     RSSI: -74 dB←[0m
←[0;36m[D][wifi:389]: - ←[5m''←[6m ←[5m(7A:8A:20:D7:8E:5C) ←[6m←[0;32mÔûéÔûäÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m''←[6m ←[5m(FE:EC:DA:11:F4:28) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m''←[6m ←[5m(1A:E8:29:EA:48:9A) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m'faasse'←[6m ←[5m(98:DA:C4:71:B3:AC) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m'ZyXELE48320'←[6m ←[5m(18:D6:C7:8A:A1:90) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m'faasse'←[6m ←[5m(64:D1:A3:34:70:0E) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m'Paul Thuis'←[6m ←[5m(64:D1:A3:33:15:F8) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m''←[6m ←[5m(FA:8F:CA:33:E9:D7) ←[6m←[0;33mÔûéÔûä←[0;37mÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m'Sitecom43A294'←[6m ←[5m(64:D1:A3:43:A2:94) ←[6m←[0;31mÔûé←[0;37mÔûäÔûåÔûê←[0m←[0m
←[0;36m[D][wifi:389]: - ←[5m'hoppe'←[6m ←[5m(A4:2B:B0:DE:77:53) ←[6m←[0;31mÔûé←[0;37mÔûäÔûåÔûê←[0m←[0m
←[0;32m[I][wifi:194]: WiFi Connecting to 'Unifi Airport'...←[0m
←[0;32m[I][wifi:457]: WiFi Connected!←[0m
←[0;35m[C][wifi:303]:   SSID: ←[5m'Unifi Airport'←[6m←[0m
←[0;35m[C][wifi:304]:   IP Address: 172.16.5.12←[0m
←[0;35m[C][wifi:306]:   BSSID: ←[5m78:8A:20:D7:8E:5C←[6m←[0m
←[0;35m[C][wifi:307]:   Hostname: 'itho_eco_fan'←[0m
←[0;35m[C][wifi:311]:   Signal strength: -57 dB ←[0;33mÔûéÔûäÔûå←[0;37mÔûê←[0m←[0m
←[0;35m[C][wifi:315]:   Channel: 6←[0m
←[0;35m[C][wifi:316]:   Subnet: 255.255.255.0←[0m
←[0;35m[C][wifi:317]:   Gateway: 172.16.5.1←[0m
←[0;35m[C][wifi:318]:   DNS1: 172.16.1.100←[0m
←[0;35m[C][wifi:319]:   DNS2: 192.168.10.100←[0m
←[0;36m[D][wifi:466]: Disabling AP...←[0m
←[0;35m[C][ota:029]: Over-The-Air Updates:←[0m
←[0;35m[C][ota:030]:   Address: itho_eco_fan.local:8266←[0m
←[0;35m[C][ota:032]:   Using Password.←[0m
←[0;35m[C][api:022]: Setting up Home Assistant API server...←[0m
←[0;32m[I][app:059]: setup() finished successfully!←[0m
←[0;32m[I][app:105]: ESPHome version 1.15.3 compiled on Oct 30 2020, 01:10:16←[0m
←[0;35m[C][wifi:443]: WiFi:←[0m
←[0;35m[C][wifi:303]:   SSID: ←[5m'Unifi Airport'←[6m←[0m
←[0;35m[C][wifi:304]:   IP Address: 172.16.5.12←[0m
←[0;35m[C][wifi:306]:   BSSID: ←[5m78:8A:20:D7:8E:5C←[6m←[0m
←[0;35m[C][wifi:307]:   Hostname: 'itho_eco_fan'←[0m
←[0;35m[C][wifi:311]:   Signal strength: -57 dB ←[0;33mÔûéÔûäÔûå←[0;37mÔûê←[0m←[0m
←[0;35m[C][wifi:315]:   Channel: 6←[0m
←[0;35m[C][wifi:316]:   Subnet: 255.255.255.0←[0m
←[0;35m[C][wifi:317]:   Gateway: 172.16.5.1←[0m
←[0;35m[C][wifi:318]:   DNS1: 172.16.1.100←[0m
←[0;35m[C][wifi:319]:   DNS2: 192.168.10.100←[0m
←[0;35m[C][logger:185]: Logger:←[0m
←[0;35m[C][logger:186]:   Level: DEBUG←[0m
←[0;35m[C][logger:187]:   Log Baud Rate: 115200←[0m
←[0;35m[C][logger:188]:   Hardware UART: UART0←[0m
←[0;35m[C][captive_portal:169]: Captive Portal:←[0m
←[0;35m[C][ota:029]: Over-The-Air Updates:←[0m
←[0;35m[C][ota:030]:   Address: itho_eco_fan.local:8266←[0m
←[0;35m[C][ota:032]:   Using Password.←[0m
←[0;35m[C][api:095]: API Server:←[0m
←[0;35m[C][api:096]:   Address: itho_eco_fan.local:6053←[0m
←[0;36m[D][text_sensor:015]: 'FanSpeed': Sending state 'Low'←[0m
←[0;36m[D][text_sensor:015]: 'FanTimer': Sending state '0'←[0m
←[0;36m[D][api.connection:604]: Client 'Home Assistant 0.117.1 (172.16.1.71)' connected successfully!←[0m
←[0;36m[D][custom:175]: Unknown state←[0m
*knip*
←[0;36m[D][custom:175]: Unknown state←[0m
←[0;36m[D][text_sensor:015]: 'FanSpeed': Sending state 'Low'←[0m
←[0;36m[D][text_sensor:015]: 'FanTimer': Sending state '0'←[0m

**Comment by Scriptman** [comment]
Hallo @Uncapable,

Mijn oprechte excuses, ik heb geen e-mail bericht ontvangen van je bericht, en ik zag het kleine blauwe bolletje niet rechtsboven bij mijn account/belletje op github (Werk zelf erg veel vanaf GitLab op het moment.

Erg fijn dat je het zelf al op hebt kunnen lossen. Ik zal binnenkort eens tijd proberen vrij te maken om de code te updaten.
